package define

const (
	PRIVATE_KEY = `-----BEGIN RSA PRIVATE KEY-----
MIICXAIBAAKBgQDS8rEgEy4itwv2GAwRetjnzatwv+RCgORj9chF5AHsv1Cy5/ZN
6jBbCbtZ/gQywTsqxybZjpoSheIrZOz5mDt6TZYEM8Y3gO4DbD5tNAK2hwHhQ3h4
K5hkDcGjD8HS4n9ErZFZmQL1JuVLkiQN2AgQxXvxY+IZysN8ayLzikh4WwIDAQAB
AoGAMtjG8xlMdJe0rWQMfKYk5HMB0RKf/Zu98Y5L8PTNtfhDhmw9RXieoUMOQtnk
vysujNgmOCiUYMSeyKDyMhOMujTSE2hHuAKtGBrA/mDc+SesCB+ZRdrG0m+2eIdS
p2KwOXnFEnYfSDRLr4JCdIQeh+wBrlvHZkoO16VnggRjGTECQQD8YbCMGSVQEyzi
qcAphIHZbU/9TKPuSMw2St1MBjdsy3Gd7tQogZr05Vjq3JQtPLSiJrLimCCRMZ9c
KU2YuKT5AkEA1fjt9YJyErHK8+/D+WgVtwJMiTDxU+giERva6o77U5y2bQTWQPIr
pLiZBWbmzXk+1F6WwNntRiCClB4zhHrg8wJABAY2v3UjMCyuGYslYkQXofTpQpu3
PXRxtSfqcWzj81snG6KURXUTmHYTveL4heQi6Tb+wTg1xLrq1JhgAWBoWQJBAJan
GOwWNzkAY3QTKblt1nQvMzIY+qFoPKwtH5qspzn8idkCYdQCbkYhDuRlyjV7m4gt
PRl1lwEcHLQq+3zYg48CQEImWvBpc/fLg+c+MA6sXVbxLPr+DKqHwDX+GNe+Zgjt
Cx6CljOPdlpA/eZu7lCgOsw2+gDyHP2CIRU5/3e6qTU=
-----END RSA PRIVATE KEY-----`

	PUBLIC_KEY = `-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDS8rEgEy4itwv2GAwRetjnzatw
v+RCgORj9chF5AHsv1Cy5/ZN6jBbCbtZ/gQywTsqxybZjpoSheIrZOz5mDt6TZYE
M8Y3gO4DbD5tNAK2hwHhQ3h4K5hkDcGjD8HS4n9ErZFZmQL1JuVLkiQN2AgQxXvx
Y+IZysN8ayLzikh4WwIDAQAB
-----END PUBLIC KEY-----`
)
